language: julia
sudo: required
dist: trusty
julia:
  - 1.0 
  - 1
notifications:
  email: false
before_install:
  - sudo apt-get -qq update
after_success:
  - julia -e 'cd(Pkg.dir("ExprOptimization")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
